# Funding sources shown in the "Sponsor" button on the WinuX repository.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [IvanPavlak]
ko_fi: ivanpavlak
