#Requires -Modules Pester

BeforeAll {
	$ModuleRoot = (Get-RepositoryPath).Modules
	. (Join-Path $ModuleRoot "Tests\Get-ExpectedTestCount.ps1")

	# Writes a fake *.Tests.ps1 into the test drive and returns its path. Only the syntax tree
	# matters here - the file is never run - so the bodies stay empty.
	function New-FakeTestFile {
		param([string]$Content, [string]$Name = ("Fake_" + [guid]::NewGuid().ToString('N') + ".Tests.ps1"))
		$path = Join-Path $TestDrive $Name
		Set-Content -LiteralPath $path -Value $Content -Encoding UTF8
		$path
	}
}

Describe "Get-ExpectedTestCount" {
	Context "Plain It blocks" {
		It "counts one test per It" {
			$file = New-FakeTestFile @'
Describe "X" {
	It "a" { }
	Context "inner" {
		It "b" { }
		It "c" { }
	}
}
'@
			$result = Get-ExpectedTestCount -Path $file
			$result.Count | Should -Be 3
			$result.Resolved | Should -BeTrue
		}

		It "counts a skipped It - Pester reports it in the total" {
			$file = New-FakeTestFile @'
Describe "X" {
	It "a" -Skip { }
	It "b" { }
}
'@
			(Get-ExpectedTestCount -Path $file).Count | Should -Be 2
		}

		It "reports zero, resolved, for a file with no tests" {
			$file = New-FakeTestFile "# nothing here"
			$result = Get-ExpectedTestCount -Path $file
			$result.Count | Should -Be 0
			$result.Resolved | Should -BeTrue
		}

		It "does not mistake the word It inside a string or a comment for a test" {
			$file = New-FakeTestFile @'
Describe "X" {
	# It "commented out" { }
	It "a" { "It" | Should -Be "It" }
}
'@
			(Get-ExpectedTestCount -Path $file).Count | Should -Be 1
		}
	}

	Context "Literal case lists" {
		It "multiplies an It by the elements of an inline -ForEach array" {
			$file = New-FakeTestFile @'
Describe "X" {
	It "ships <Key>" -ForEach @{ Key = "A" }, @{ Key = "B" }, @{ Key = "C" } { }
}
'@
			(Get-ExpectedTestCount -Path $file).Count | Should -Be 3
		}

		It "counts every element of a multi-line @( ) case list" {
			$file = New-FakeTestFile @'
Describe "X" {
	It "ships <Key>" -ForEach @(
		@{ Key = "A" }
		@{ Key = "B" }
		@{ Key = "C" }, @{ Key = "D" }
	) { }
}
'@
			(Get-ExpectedTestCount -Path $file).Count | Should -Be 4
		}

		It "counts a single hashtable as one case" {
			$file = New-FakeTestFile @'
Describe "X" {
	It "ships <Key>" -ForEach @{ Key = "A" } { }
}
'@
			(Get-ExpectedTestCount -Path $file).Count | Should -Be 1
		}

		It "treats -TestCases exactly like -ForEach" {
			$file = New-FakeTestFile @'
Describe "X" {
	It "ships <Key>" -TestCases @( @{ Key = "A" }, @{ Key = "B" } ) { }
}
'@
			(Get-ExpectedTestCount -Path $file).Count | Should -Be 2
		}

		It "multiplies every It inside a Describe or Context that carries a literal -ForEach" {
			$file = New-FakeTestFile @'
Describe "X <Name>" -ForEach @( @{ Name = "one" }, @{ Name = "two" } ) {
	It "a" { }
	Context "Y <Mode>" -ForEach @{ Mode = 1 }, @{ Mode = 2 }, @{ Mode = 3 } {
		It "b" { }
		It "c" -ForEach @( @{ Z = 1 }, @{ Z = 2 } ) { }
	}
}
'@
			# a: 2, b: 2 * 3, c: 2 * 3 * 2
			(Get-ExpectedTestCount -Path $file).Count | Should -Be 20
		}
	}

	Context "Counts that only discovery can settle" {
		It "marks the file unresolved when an It takes its cases from a variable, and still counts the rest" {
			$file = New-FakeTestFile @'
$Modules = Get-ChildItem -Directory
Describe "X" {
	It "plain" { }
	It "module <_>" -ForEach $Modules { }
}
'@
			$result = Get-ExpectedTestCount -Path $file
			$result.Resolved | Should -BeFalse
			$result.Count | Should -Be 1
		}

		It "marks the file unresolved when an enclosing block's -ForEach is computed" {
			$file = New-FakeTestFile @'
Describe "X <_>" -ForEach (Get-ChildItem -Directory) {
	It "a" { }
}
Describe "Y" {
	It "b" { }
}
'@
			$result = Get-ExpectedTestCount -Path $file
			$result.Resolved | Should -BeFalse
			$result.Count | Should -Be 1
		}

		It "marks the file unresolved when an It is generated by a loop" {
			$file = New-FakeTestFile @'
Describe "X" {
	foreach ($case in 1..5) {
		It "case $case" { }
	}
	It "fixed" { }
}
'@
			$result = Get-ExpectedTestCount -Path $file
			$result.Resolved | Should -BeFalse
			$result.Count | Should -Be 1
		}

		It "marks the file unresolved when an It lives inside a helper function" {
			$file = New-FakeTestFile @'
function Add-CommonTests { It "shared" { } }
Describe "X" {
	Add-CommonTests
	It "own" { }
}
'@
			$result = Get-ExpectedTestCount -Path $file
			$result.Resolved | Should -BeFalse
			$result.Count | Should -Be 1
		}
	}

	Context "Tags and -ExcludeTag" {
		It "reports every literal tag in the file and counts everything when nothing is excluded" {
			$file = New-FakeTestFile @'
Describe "X" -Tag 'Integration' {
	It "a" { }
	Context "Y" -Tag 'Slow', 'Git' {
		It "b" -Tag @('Deep') { }
	}
}
'@
			$result = Get-ExpectedTestCount -Path $file
			$result.Count | Should -Be 2
			$result.Excluded | Should -Be 0
			$result.Resolved | Should -BeTrue
			@($result.Tags | Sort-Object) | Should -Be @('Deep', 'Git', 'Integration', 'Slow')
		}

		It "leaves out every test under an excluded Describe tag, reporting them in Excluded" {
			$file = New-FakeTestFile @'
Describe "X" -Tag 'Integration' {
	It "a" { }
	It "b" -ForEach @{ N = 1 }, @{ N = 2 } { }
}
Describe "Y" {
	It "c" { }
}
'@
			$result = Get-ExpectedTestCount -Path $file -ExcludeTag 'Integration'
			$result.Count | Should -Be 1
			$result.Excluded | Should -Be 3
			$result.Resolved | Should -BeTrue
		}

		It "leaves out a test whose own tag or whose Context tag is excluded, case-insensitively" {
			$file = New-FakeTestFile @'
Describe "X" {
	It "kept" { }
	It "own tag" -Tag 'integration' { }
	Context "C" -Tag 'Integration' {
		It "context tag" { }
	}
}
'@
			$result = Get-ExpectedTestCount -Path $file -ExcludeTag 'Integration'
			$result.Count | Should -Be 1
			$result.Excluded | Should -Be 2
		}

		It "honours a wildcard in -ExcludeTag" {
			$file = New-FakeTestFile @'
Describe "X" -Tag 'IntegrationGit' {
	It "a" { }
}
Describe "Y" { It "b" { } }
'@
			(Get-ExpectedTestCount -Path $file -ExcludeTag 'Integration*').Count | Should -Be 1
		}

		It "marks the file unresolved when a tag is computed and something is excluded" {
			$file = New-FakeTestFile @'
$tags = 'Integration'
Describe "X" -Tag $tags {
	It "a" { }
}
Describe "Y" { It "b" { } }
'@
			$result = Get-ExpectedTestCount -Path $file -ExcludeTag 'Integration'
			$result.Resolved | Should -BeFalse
			$result.Count | Should -Be 1
		}

		It "ignores a computed tag when nothing is excluded" {
			$file = New-FakeTestFile @'
$tags = 'Integration'
Describe "X" -Tag $tags {
	It "a" { }
}
'@
			$result = Get-ExpectedTestCount -Path $file
			$result.Resolved | Should -BeTrue
			$result.Count | Should -Be 1
		}
	}

	Context "Several files" {
		It "returns one row per file, in the order given, carrying the path" {
			$first = New-FakeTestFile 'Describe "A" { It "a" { } }' -Name "First.Tests.ps1"
			$second = New-FakeTestFile 'Describe "B" { It "a" { }; It "b" { } }' -Name "Second.Tests.ps1"
			$rows = @(Get-ExpectedTestCount -Path $first, $second)
			$rows.Count | Should -Be 2
			$rows[0].Path | Should -Be $first
			$rows[0].Count | Should -Be 1
			$rows[1].Path | Should -Be $second
			$rows[1].Count | Should -Be 2
		}

		It "returns nothing for an empty path list" {
			@(Get-ExpectedTestCount -Path @()).Count | Should -Be 0
		}
	}
}
